version: "1.0"
info:
  model: int-scaffold
packages:
- name: SimpleWebMethodsPKGsProject
  gitServerName: emea02user_avivsimds_public_github
  gitUrl: https://github.com/AvivSimDS/SimpleWebMethodsPKGsProject
  gitUsername: AvivSimDS
  gitBranch: main
